name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=ghcr.io/darsh12/awx-ee:${{ github.event.release.tag_name }}

      - name: Apply latest tag
        run: |
         docker tag ghcr.io/darsh12/awx-ee:${{ github.event.release.tag_name }} ghcr.io/darsh12/awx-ee:latest

      - name: Push images
        run: |
         echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
         docker push ghcr.io/darsh12/awx-ee:${{ github.event.release.tag_name }}
         docker push ghcr.io/darsh12/awx-ee:latest
